### PR TITLE
Update auctions_ended.md

### PR DESCRIPTION
**Pull request by ChiefChippy2**
Cache Control header doesn't give any info, but rather the age header

### CODE REVIEW

**Comment by ThomDeMeulder** [comment]
Hello, I think they are referring to the Skyblock auctions that have ended in the last _X_ seconds with the _Cache-Control_ header indicating the maximum time in seconds. The _Age_ header seems to indicate how long Cloudflare has been caching the response in seconds. It isn't always present because not all responses are being cached by Cloudflare. For example when the _Cache-Control_ header's expire time has been reached. I would assume this has been done so they can change the caching amount if needed.

Which would mean that saying the _Age_ header indicating how long ago the ended auctions could possibly be from is not true. This can be verified by looking at the _Age_ header, it keeps updating every request to match how long it has been cached. If you then would lets say wait 1 minute and 30 seconds, and then make 2 requests it will display an _Age_ header of 1 or 2. If you however then look at the response body and to be precise the "lastUpdated" field this could be completely something else, such as 37 seconds ago. So you should use the "lastUpdated" field to determine when it has been updated.

Take a look at these pages from the Cloudflare support team:
https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN
https://support.cloudflare.com/hc/en-us/articles/115003206852-Understanding-Origin-Cache-Control

If anyone thinks I'm wrong let me know. But to my knowledge the information in the file is correct.

**Comment by ChiefChippy2** [comment]
AFAIK the age header is present when cloudflare returns a cached response.
I guess I have to change what I wrote because as you said, age doesn't exactly mean that, but rather how long the response will be cached before it gets refreshed.
Also, the Cache Control header doesn't provide that info ( of Skyblock auctions that have ended in the last X seconds ). I just did a test, and one SB Auction ended 64 seconds ago but is still present with Cache Control at 60. I guess that is a very general guideline of how long the oldest sb auction in the list of ended ones can be.

**Comment by ThomDeMeulder** [comment]
> AFAIK the age header is present when cloudflare returns a cached response.
> I guess I have to change what I wrote because as you said, age doesn't exactly mean that, but rather how long the response will be cached before it gets refreshed.
> Also, the Cache Control header doesn't provide that info ( of Skyblock auctions that have ended in the last X seconds ). I just did a test, and one SB Auction ended 64 seconds ago but is still present with Cache Control at 60. I guess that is a very general guideline of how long the oldest sb auction in the list of ended ones can be.

But couldn't it be the case that the auction that is 64 seconds old is in there because of the cloudflare cache, so meanwhile the Hypixel servers have updated it but you are still getting a cached response?

**Comment by ChiefChippy2** [comment]
> > AFAIK the age header is present when cloudflare returns a cached response.
> > I guess I have to change what I wrote because as you said, age doesn't exactly mean that, but rather how long the response will be cached before it gets refreshed.
> > Also, the Cache Control header doesn't provide that info ( of Skyblock auctions that have ended in the last X seconds ). I just did a test, and one SB Auction ended 64 seconds ago but is still present with Cache Control at 60. I guess that is a very general guideline of how long the oldest sb auction in the list of ended ones can be.
> 
> But couldn't it be the case that the auction that is 64 seconds old is in there because of the cloudflare cache, so meanwhile the Hypixel servers have updated it but you are still getting a cached response?

Nope because I checked it with the lastUpdatedTimestamp
also cache was expired (  cf-cache-status: EXPIRED = ENDED and no age )

**Comment by ConnorLinfoot** [comment]
Closing this as we no longer use GitHub for the documentation and host an OpenAPI spec at https://api.hypixel.net

**Pull request closed without merging**
