### PR TITLE
Add Warlords

### PR DESCRIPTION
**Pull request by njb-said**
not sure on the id

### CODE REVIEW

**Comment by palechip** [comment]
The id is 23.

**Comment by njb-said** [comment]
@palechip 
Thanks for that link, didn't even know it existed! :smile:

**Comment by KevyPorter** [comment]
I did this 5 days ago xd
https://github.com/HypixelDev/PublicAPI/pull/13
Still not updated xddd

**Comment by Cryptkeeper** [comment]
Added in 38e5f2ef3a503f238e90039dc539654052548345.

**Pull request closed without merging**
