### PR TITLE
Cleaned up Most reply API and util API

### PR DESCRIPTION
**Pull request by yawn999**
Code cleanup most of the reply API.

Its not the best but I did move some things and decided to spread a few things out.

### CODE REVIEW

**Comment by TheNullicorn** [comment]
Have you made any changes to the code, or is it just reformatted? Some more details would be nice.

This is subjective, but I'm not sure I like some of the reformatting. For example the expanded `EXPERIENCE_LEVELS` array in `Pet.java`, which you now have to scroll past to get to the class itself.

**Comment by yawn999** [comment]
its just a small cleanup. nothing new to the code.

**Comment by ConnorLinfoot** [comment]
As this doesn't provide any gain to the project, this isn't something we wish to merge. The code style that is used is primarily based on the default within IntelliJ, and I don't think it makes sense to make changes to this.

**Comment by yawn999** [comment]
no worries.

**Pull request closed without merging**
