### PR TITLE
Added tagColor to Guild

### PR DESCRIPTION
**Pull request by fratik**
This field is returned by the API but not included in this library

### CODE REVIEW

**Comment by fratik** [comment]
Like this?

**Comment by mdashlw** [comment]
I think this enum should be renamed to something like `MinecraftColor`, as it exposes all the colors in minecraft, not just the guild tag colors.

**Comment by fratik** [comment]
👌

**Comment by Cleymax** [comment]
👍

**Comment by ConnorLinfoot** [comment]
We don't want to be adding more enums of colors to downstream projects. If this is something people need they should be adding it to the projects themselves.

**Pull request closed without merging**
