### PR TITLE
Remove outdated statement

### PR DESCRIPTION
**Pull request by mdashlw**

### CODE REVIEW

**Comment by ConnorLinfoot** [comment]
This is not correct, the information is still correct

**Comment by mdashlw** [comment]
> This is not correct, the information is still correct

It was never correct, here's an example
image

**Comment by ConnorLinfoot** [comment]
SkyWars ranked was an exception to this rule, which has already been fixed from the API.

**Comment by mdashlw** [comment]
> SkyWars ranked was an exception to this rule, which has already been fixed from the API. This information is still correct, and if there is anything outside of this then it is likely to be a bug and changing the documentation is not the fix.

Another example with the other games. I assume you fixed it just now, because now I don't see old games for those players.
image

Either way, it should probably be documented at https://api.hypixel.net/#tag/Player-Data/paths/~1recentgames/get as well.

**Pull request closed without merging**
